baseURL = 'https://matteo.vaccari.name/'
languageCode = 'en'
title = "Matteo Vaccari"
theme = 'hugo-simple'
copyright = "© 2001-2024 Matteo Vaccari"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]

[taxonomies]
tag = "tags"


[permalinks]
blog = "/:slugorfilename/"
tags = "/posts/:slug"


[params]
description = "A collection of writings about software development"
favicon = "favicon.ico"
dateFormat = "2006-01-02"
hideMadeWithLine = true

[params.author]
name = "Matteo Vaccari"
email = "vaccari@pobox.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 20
[[menu.main]]
name = "About"
pageRef = "/about"
weight = 30

[services.rss]
limit = 42

[outputs]
# Disable section RSS
section = ["html"]

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = false
lineNumbersInTable = false
noClasses = false
#style="catppuccin-mocha"

[pagination]
disableAliases = false
pagerSize = 50
path = 'page'


